<a href="https://colab.research.google.com/github/010Ankushsharma/STATISTICAL-COMPUTATION-USING-NUMPY/blob/main/statistical_analysis_on_iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **STATISTICAL COMPUTATION USING NUMPY**

> created by:  
*  Ankush Sharma  
*  Harmanpreet Singh  
*  Rahul Kumar  
*  Shivjot   
*  Amandeep
*  Karan Kumar








In [3]:
#importing packages numpy
import numpy as np

In [4]:
#loading iris dataset
from sklearn.datasets import load_iris

In [5]:
#loading data and features into variables
iris=load_iris()
x=iris.data
features_name= iris.feature_names

In [6]:
#calculated mean
mean_value= np.mean(x)
print("This is the airthmatical mean : ",mean_value)

mean_value_contains_nan= np.nanmean(x)    #this function skips nan values and compute mean for the remaining values
print("This is the airthmatical mean with nan : ",mean_value_contains_nan)


This is the airthmatical mean :  3.4644999999999997
This is the airthmatical mean with nan :  3.4644999999999997


**Mean analysis**

to find central tendency

In [7]:
#calculated median
median_value= np.median(x)
print("This is the median : ",median_value)

median_value_contains_nan= np.nanmedian(x)    #this function skips nan values and compute median for the remaining values
print("This is the median with nan : ",median_value_contains_nan)


This is the median :  3.2
This is the median with nan :  3.2


**MEDIAN analysis**

median is less affected from outliers  
mean ~ median = data is not heavly skewed

In [8]:
#calculated variance
variance= np.var(x)
print("This is the variance : ",variance)

nan_variance= np.nanvar(x)    #this function skips nan values and compute variance for the remaining values
print("This is the variance with nan : ",nan_variance)

This is the variance :  3.896056416666667
This is the variance with nan :  3.896056416666667


**Variance Analysis**  
* It shows how spread out the data is around its mean
* high variance value signifies widely spread data  
* low variance value signifies tighly packed values
* if the value is zero then the data points are identical

 > **Conclusion** : High varience means it varies the most among the flowers

In [9]:
#calculated standard_deviation
standard_deviation= np.std(x)
print("This is the standard_deviation : ",standard_deviation)

nan_standard_deviation= np.nanstd(x)    #this function skips nan values and compute standard_deviation for the remaining values
print("This is the standard_deviation with nan : ",nan_standard_deviation)

This is the standard_deviation :  1.9738430577598278
This is the standard_deviation with nan :  1.9738430577598278


**Standard deviation Analysis**  
* It shows how spread out the data is around its mean
* high variance value signifies widely spread data  
* low variance value signifies tighly packed values
* if the value is zero then the data points are identical

 > **Conclusion** : how much data is divided form the mean  
 more std features has more variability

In [10]:
print(np.min(x)), print(np.max(x)) # printing max and min

0.1
7.9


(None, None)

In [11]:
range_value=np.ptp(x)    # peek to peek
print("This is the range : ",range_value)
# max- min= ptp

This is the range :  7.800000000000001


In [12]:
Q1 = np.percentile(x, 25, axis=0)
Q3 = np.percentile(x, 75, axis=0)
IQR = Q3 - Q1
print("This is the Q1 : ",Q1)
print("This is the Q3 : ",Q3)
print("This is the IQR : ",IQR)

This is the Q1 :  [5.1 2.8 1.6 0.3]
This is the Q3 :  [6.4 3.3 5.1 1.8]
This is the IQR :  [1.3 0.5 3.5 1.5]


**percentile analysis**
  IOR capture the middle 50%  
  usedull for detecting outliers  

In [13]:
cov_matrix=np.cov(x.T)

print("this is covarience matrix for data set : \n",cov_matrix)

this is covarience matrix for data set : 
 [[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


**Covarience analysis**  
it tells teh direction of relationship between features

In [14]:
corr_matrix=np.corrcoef(x.T)
print("this is Corelation matrix for data set : \n",corr_matrix)

this is Corelation matrix for data set : 
 [[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


**Corelation analysis**  
Correlation is normalized covariance (range -1 to 1).  
Petal length & width are strongly correlated → important for feature selection.

In [17]:
Z = (x- mean_value) / standard_deviation
print ("Z- mean: ",np.mean(Z))
print("Z-Std: ",np.std(Z))

Z- mean:  1.1842378929335003e-16
Z-Std:  1.0


** Z-Score**  
After normalization:  
Mean ≈ 0  
Std ≈ 1  
This is essential for algorithms like KNN, SVM, Gradient Descent.


In [18]:
skewness = np.mean((x - mean_value)**3) / (standard_deviation**3)
print ("skewness is : ",skewness)

skewness is :  0.12694978684432776


**Skewness analysis**   
Skewness tells us if data is symmetric or skewed.    
Low skew → near-normal distribution

##**Class-wise Statistical Analysis (Flower Type Wise)**

The Iris dataset has 3 flower species:  
Setosa (0)  
Versicolor (1)  
Virginica (2)  
We now perform statistical operations separately for each flower type and compare them

In [20]:
y=iris.target

In [21]:
setosa = x[y == 0]
versicolor = x[y == 1]
virginica = x[y == 2]

Splitting the dataset allows us to understand how each species differs statistically, which is crucial for classification problems.

In [29]:
mean_setosa = np.mean(setosa, axis=0)
mean_versicolor = np.mean(versicolor, axis=0)
mean_virginica = np.mean(virginica, axis=0)
print(mean_setosa)
print(mean_versicolor)
print(mean_virginica)

[5.006 3.428 1.462 0.246]
[5.936 2.77  4.26  1.326]
[6.588 2.974 5.552 2.026]


**Mean Comparison analysis**
Setosa has smallest petal length & width  
Virginica has largest petal features  
Versicolor lies in between

In [22]:
std_setosa = np.std(setosa, axis=0)
std_versicolor = np.std(versicolor, axis=0)
std_virginica = np.std(virginica, axis=0)
print(std_setosa)
print(std_versicolor)
print(std_virginica)



[0.34894699 0.37525458 0.17191859 0.10432641]
[0.51098337 0.31064449 0.46518813 0.19576517]
[0.62948868 0.31925538 0.54634787 0.27188968]


**Standard Deviation Comparison analysis**  
Setosa shows lowest variability → more compact cluster  
Virginica shows higher variability → more spread out  
Lower std means easier separation by ML models.

In [23]:
var_setosa = np.var(setosa, axis=0)
var_versicolor = np.var(versicolor, axis=0)
var_virginica = np.var(virginica, axis=0)
print(var_setosa)
print(var_versicolor)
print(var_virginica)



[0.121764 0.140816 0.029556 0.010884]
[0.261104 0.0965   0.2164   0.038324]
[0.396256 0.101924 0.298496 0.073924]


**Variance Comparison analysis**  
Petal length variance increases from Setosa → Versicolor → Virginica, showing gradual complexity.

In [24]:
range_setosa = np.ptp(setosa, axis=0)
range_versicolor = np.ptp(versicolor, axis=0)
range_virginica = np.ptp(virginica, axis=0)
print(range_setosa)
print(range_versicolor)
print(range_virginica)


[1.5 2.1 0.9 0.5]
[2.1 1.4 2.1 0.8]
[3.  1.6 2.4 1.1]


**Range Comparison (Max − Min)  analysis**  
Virginica has the widest range, meaning its measurements vary more widely.

In [25]:
corr_setosa = np.corrcoef(setosa.T)
corr_versicolor = np.corrcoef(versicolor.T)
corr_virginica = np.corrcoef(virginica.T)
print(corr_setosa)
print(corr_versicolor)
print(corr_virginica)



[[1.         0.74254669 0.26717576 0.27809835]
 [0.74254669 1.         0.17769997 0.23275201]
 [0.26717576 0.17769997 1.         0.33163004]
 [0.27809835 0.23275201 0.33163004 1.        ]]
[[1.         0.52591072 0.75404896 0.54646107]
 [0.52591072 1.         0.56052209 0.66399872]
 [0.75404896 0.56052209 1.         0.78666809]
 [0.54646107 0.66399872 0.78666809 1.        ]]
[[1.         0.45722782 0.86422473 0.28110771]
 [0.45722782 1.         0.40104458 0.53772803]
 [0.86422473 0.40104458 1.         0.32210822]
 [0.28110771 0.53772803 0.32210822 1.        ]]


**Correlation Analysis per Species**  
 Strong petal length–width correlation in all species  
Correlation strength increases from Setosa to Virginica

In [30]:
Z_setosa = (setosa - mean_setosa) / std_setosa
Z_versicolor = (versicolor - mean_versicolor) / std_versicolor
Z_virginica = (virginica - mean_virginica) / std_virginica
print(Z_setosa)
print(Z_versicolor)
print(Z_virginica)


[[ 0.26938189  0.19186974 -0.36063582 -0.44092382]
 [-0.30377107 -1.14055903 -0.36063582 -0.44092382]
 [-0.87692403 -0.60758752 -0.9423065  -0.44092382]
 [-1.16350052 -0.87407328  0.22103486 -0.44092382]
 [-0.01719459  0.4583555  -0.36063582 -0.44092382]
 [ 1.12911134  1.25781276  1.38437621  1.47613628]
 [-1.16350052 -0.07461601 -0.36063582  0.51760623]
 [-0.01719459 -0.07461601  0.22103486 -0.44092382]
 [-1.73665348 -1.40704478 -0.36063582 -0.44092382]
 [-0.30377107 -0.87407328  0.22103486 -1.39945388]
 [ 1.12911134  0.72484125  0.22103486 -0.44092382]
 [-0.59034755 -0.07461601  0.80270553 -0.44092382]
 [-0.59034755 -1.14055903 -0.36063582 -1.39945388]
 [-2.02322996 -1.14055903 -2.10564785 -1.39945388]
 [ 2.27541727  1.52429852 -1.52397717 -0.44092382]
 [ 1.98884078  2.59024154  0.22103486  1.47613628]
 [ 1.12911134  1.25781276 -0.9423065   1.47613628]
 [ 0.26938189  0.19186974 -0.36063582  0.51760623]
 [ 1.98884078  0.99132701  1.38437621  0.51760623]
 [ 0.26938189  0.99132701  0.22

**Z-Score Normalization per Species analysis**  
Each species becomes centered at 0 with unit variance, allowing fair comparison.

# Statistical Insights

✔ Setosa is linearly separable due to low variance    
✔ Versicolor & Virginica overlap → harder classification  
✔ Petal features dominate decision boundaries  
✔ Sepal features alone are insufficient